
# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "clippy"

[jobs]

[jobs.clippy]
command = [
    "cargo",
    "clippy",
    "--color",
    "always",
    "--workspace",
    "--all-targets",
    "--all-features",
]
need_stdout = false

[jobs.test]
command = [
    "cargo",
    "test",
    "--color",
    "always",
    "--workspace",
    "--all-targets",
    "--all-features",
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

# if the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"                                                    # so that we don't open the browser at each change

[keybindings]
d = "job:doc-open"
i = "job:initial"
t = "job:test"
